AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'vendor/*'
    - 'spec/**/*'
    - '*.gemspec'

AbcSize:
  Max: 20

Performance:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Style/BlockComments:
  Enabled: false
