require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2

AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Performance:
  Enabled: true

Style/WordArray:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 10

Style/BlockComments:
  Enabled: false
