language: ruby
sudo: required
rvm: 2.4.1

env:
  - TRANSFER_TO_INKIND_API_KEY='' TRANSFER_TO_INKIND_API_SECRET='' TRANSFER_TO_INKIND_ENDPOINT='https://api.transferto.com/v1.1'

cache:
  - bundler

script:
  - bundle install
  - bundle exec rspec
