require 'faraday'
require 'net/http'
require 'openssl'
require 'base64'

require 'inkind/version'
require 'inkind/exception'
require 'inkind/client'
require 'inkind/entities/service'
require 'inkind/entities/country'
require 'inkind/entities/operator'
require 'inkind/entities/product'
